### ISSUE TITLE
Support for type hinting generics In standard collections

### ISSUE THREAD

**Issue by GentleEnvy** [EvgeniyBurdin/validated_dc#1]
Since Python 3.9, you can specify built-in types in generics, instead of duplicates from the typing module. For example `typing.List` and the built-in `list`. Now this library can only work with duplicates from typing.

```python
@dataclass
class Data(ValidatedDC):
    ints: list[int]

Data([1]).get_errors()  # {'ints': [BasicValidationError(value_repr='[1]', value_type=<class 'list'>, annotation=list[int],
                        # exception=TypeError('isinstance() argument 2 cannot be a parameterized generic'))]}

**Comment by EvgeniyBurdin** [comment]
Yes I know that. But I don’t plan to change anything yet, because it’s not yet clear how work with annotations will be organized in future versions of python
