### ISSUE TITLE
Support for other built-in collections

### ISSUE THREAD

**Issue by GentleEnvy** [EvgeniyBurdin/validated_dc#2]
Are you planning to add support for set, tuple, dict, etc. ?
Like this
```python
@dataclasses.dataclass
class Data(ValidatedDC):
    ints: Set[int]
    strs: Tuple[str]
    map: Dict[str, int]
```

**Comment by EvgeniyBurdin** [comment]
At the moment there are no such plans.
This is due to the fact that work with annotations may change in new versions of python. I decided to wait for now :)

Initially, this module was created only to validate the types supported in json. And these types are supported.
